AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25
